name: cognite-python-sdk CI no 3.5
# RERUN
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:      
  build_and_test_python:
    runs-on: ubuntu-latest
    steps:
    - name: checkout src code from repo
      uses: actions/checkout@v2
    - name: Test Core
      env:
        COGNITE_API_KEY: ${{ secrets.integration_test_api_key }}
        CODECOV_TOKEN: ${{ secrets.cognite_sdk_python }}
        COGNITE_BASE_URL: https://greenfield.cognitedata.com
        COGNITE_CLIENT_NAME: python-sdk-integration-tests
        COGNITE_PROJECT: python-sdk-test
        CI: '1'
        BRANCH_NAME: ${GITHUB_REF##*/}
      uses: ./.github/actions/test_python_3_5_0