name: HACKY CI
# RERUN
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build_deref_spec: 
    runs-on: ubuntu-latest
    container: node:10-slim
    steps:
    - name: Install dependencies for swagger-cli
      shell: bash
      run: |
        apt-get update && apt-get install -y curl && \
        npm install -g swagger-cli@3.0.1 && \
        curl 'https://storage.googleapis.com/cognitedata-api-docs/dist/v1.json' --output spec.json --compressed
    - name: Generate deref spec
      shell: bash
      run: |
        swagger-cli bundle -r spec.json -o deref-spec.json
    - name: Upload deref as artifact
      uses: actions/upload-artifact@v1
      with:
        name: deref-spec
        path: deref-spec.json
      
  build_and_test_python:
    needs: build_deref_spec
    runs-on: ubuntu-latest
    container:
      image: python:3.7.6-stretch
    steps:
    - name: Download the deref-spec for API testing 
      uses: actions/download-artifact@v1
      with:
        name: deref-spec
    - name: Build the environment 
      run: |
        export PATH="/github/home/.pyenv/bin:$PATH" 
        apt-get update && \
        apt-get purge libssl-dev -y && \
        apt-get install libssl1.0-dev -y && \
        curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash && \
        pyenv install 3.5.0 && \
        pyenv install 3.6.6 && \
        pyenv install 3.7.6 && \
        pyenv install 3.8.0
      shell: bash
      env: 
        PYTHON_3_5: /root/.pyenv/versions/3.5.0/bin/python
        PYTHON_3_6: /root/.pyenv/versions/3.6.6/bin/python
        PYTHON_3_7: /root/.pyenv/versions/3.7.6/bin/python
        PYTHON_3_8: /root/.pyenv/versions/3.8.0/bin/python
    - name: Install Pipenv
      run: |
        pip3 install pipenv
    - name: checkout src code
      uses: actions/checkout@v2
    - name: Install core dependencies
      run: |
        pipenv run pip install -r core-requirements.txt
    - name: Test Core
      env:
        COGNITE_API_KEY: ${{ secrets.integration_test_api_key }}
        CODECOV_TOKEN: ${{ secrets.cognite_sdk_python }}
        COGNITE_BASE_URL: https://greenfield.cognitedata.com
        COGNITE_CLIENT_NAME: python-sdk-integration-tests
        COGNITE_PROJECT: python-sdk-test
        CI: '1'
        BRANCH_NAME: ${GITHUB_REF##*/}
      run: |
        pipenv run pytest tests/tests_unit -m 'not dsl' --test-deps-only-core


